### ISSUE TITLE
cannot create a pipeline between MongoDB and NEO4j

### ISSUE THREAD

**Issue by grv1207** [neo4j-contrib/neo4j_doc_manager#71]
after typing " mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager " I get following error,
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/gauravvashisth/anaconda/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/gauravvashisth/anaconda/lib/python3.5/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/Users/gauravvashisth/anaconda/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 267, in run
    docman.upsert(doc, ns, timestamp)
  File "/Users/gauravvashisth/anaconda/lib/python3.5/site-packages/mongo_connector/doc_managers/neo4j_doc_manager.py", line 66, in upsert
    tx.commit()
  File "/Users/gauravvashisth/anaconda/lib/python3.5/site-packages/py2neo/cypher/core.py", line 306, in commit
    return self.post(self.__commit or self.__begin_commit)
  File "/Users/gauravvashisth/anaconda/lib/python3.5/site-packages/py2neo/cypher/core.py", line 261, in post
    raise self.error_class.hydrate(error)
  File "/Users/gauravvashisth/anaconda/lib/python3.5/site-packages/py2neo/cypher/error/core.py", line 54, in hydrate
    error_cls = getattr(error_module, title)
AttributeError: module 'py2neo.cypher.error.schema' has no attribute 'ConstraintValidationFailed'

I have installed py2neo 2.0.7

**Comment by n1t1nK** [comment]
i faced the same problem, you are violating some constraint for me it was uniqueness constraint.

**Comment by hhongwen** [comment]
i faced the same problem, too...
how did you solve the problem?
