### ISSUE TITLE
5.0b1 py2neo and 4.1.1 .. a quick fix ? do I back to a older py2neo version ?  doc manager connect issues- Customer on my back

### ISSUE THREAD

**Issue by johnda98** [neo4j-contrib/neo4j_doc_manager#82]
leveridge@leveridge-PowerEdge-R710:~$ py2neo version
5.0b1
leveridge@leveridge-PowerEdge-R710:~$ mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager
Traceback (most recent call last):
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/connector.py", line 1098, in import_dm_by_path
    module = __import__(package, fromlist=(package,))
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/doc_managers/neo4j_doc_manager.py", line 16, in <module>
    from py2neo import Graph, authenticate
  File "/home/leveridge/.local/lib/python3.6/site-packages/py2neo/__init__.py", line 19, in <module>
    from py2neo.data import *
  File "/home/leveridge/.local/lib/python3.6/site-packages/py2neo/data/__init__.py", line 25, in <module>
    from py2neo.collections import is_collection, SetView, PropertyDict
ImportError: cannot import name 'PropertyDict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/leveridge/.local/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/util.py", line 107, in wrapped
    func(*args, **kwargs)
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/connector.py", line 1409, in main
    conf.parse_args()
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/config.py", line 125, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names)
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/connector.py", line 1122, in apply_doc_managers
    DocManager = import_dm_by_name(dm["docManager"])
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/connector.py", line 1089, in import_dm_by_name
    return import_dm_by_path(full_name)
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/connector.py", line 1109, in import_dm_by_path
    "vailable doc managers. ImportError:\n%s" % (package, exc)
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.neo4j_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers. ImportError:
cannot import name 'PropertyDict'

**Comment by mihirkhandekar** [comment]
Is this repository maintained? 
Did you find a solution to this issue? It's been quite a while since this has been raised.
